### ISSUE TITLE
Meeting Time????

### ISSUE THREAD

**Issue by biancamaginley** [ChinoyIndustries/WoodburyClayCo#1]
Hey when do we want to meet up for the project?

**Comment by robftg** [comment]
I can do any day around mid day

**Comment by biancamaginley** [comment]
@ChinoyIndustries What about you?

**Comment by biancamaginley** [comment]
Okay so tentative meeting time for this week: Friday at 12?

**Comment by robftg** [comment]
> Okay so tentative meeting time for this week: Friday at 12?

I'm Fine with this

**Comment by biancamaginley** [comment]
@ChinoyIndustries ????

**Comment by ebeshero** [comment]
@biancamaginley We are prodding him on the instructor chat, as well, so far without success.

**Comment by frabbitry** [comment]
@biancamaginley @robftg 
I'm also free tomorrow at noon; what if I met with you guys? I can talk to you both about some things that you guys can do so that neither of you falls behind in the class. 

Where would be a good place to meet?

**Comment by biancamaginley** [comment]
@frabbitry as long as no one else is in there, can we use the room in FOB?

**Comment by frabbitry** [comment]
Yeah, I don't think that anyone will be in there. Brad I believe has office hours only on Mondays and Wednesdays. 

So, yes, we can use FOB 131.

**Comment by frabbitry** [comment]
Is that all good with both of you? Meet tomorrow at noon in FOB 131?

Let me know if you can't find it. I think Dr. B left some directions in the initial announcement she made on Canvas about the Instructor office hours.

**Comment by robftg** [comment]
Thats fine with me

**Comment by biancamaginley** [comment]
See you then!

**Comment by BMT45** [comment]
I hold office hours from 11-1 on Monday, Wednesday, and Friday.   You are more than welcome to come in at noon and I can help you anyway I can as well!
